export const PRODUCTS = [
  { id: '1', name: 'Ultra Widget', price: 129 },
  { id: '2', name: 'Mega Gadget', price: 249 },
  { id: '3', name: 'Super Gizmo', price: 399 },
  { id: '4', name: 'Nano Device', price: 89 },
  { id: '5', name: 'Quantum Tool', price: 559 },
  { id: '6', name: 'Hyper Accessory', price: 179 },
  { id: '7', name: 'Alpha Gear', price: 320 },
  { id: '8', name: 'Beta Component', price: 210 },
  { id: '9', name: 'Gamma Module', price: 275 },
  { id: '10', name: 'Delta Part', price: 150 },
  { id: '11', name: 'Epsilon Unit', price: 480 },
  { id: '12', name: 'Zeta Engine', price: 620 },
  { id: '13', name: 'Theta Chip', price: 95 },
  { id: '14', name: 'Sigma Board', price: 340 },
  { id: '15', name: 'Omega Frame', price: 410 },
  { id: '16', name: 'Lambda Panel', price: 230 },
  { id: '17', name: 'Kappa Sensor', price: 199 },
  { id: '18', name: 'Pi Controller', price: 370 },
  { id: '19', name: 'Rho Adapter', price: 145 },
  { id: '20', name: 'Tau Connector', price: 285 },
];
